// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SnlMaps.Web.Database;

namespace SnlMaps.Web.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("SnlMaps.Domain.City", b =>
                {
                    b.Property<string>("InseeCode")
                        .HasColumnType("text");

                    b.Property<Polygon>("Geometry")
                        .HasColumnType("geometry");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("PostCode")
                        .HasColumnType("text");

                    b.Property<int>("SnlHousingCount")
                        .HasColumnType("integer");

                    b.Property<int>("SocialHousingCount")
                        .HasColumnType("integer");

                    b.Property<decimal>("SocialHousingRate")
                        .HasColumnType("numeric");

                    b.Property<bool>("SruDeficit")
                        .HasColumnType("boolean");

                    b.HasKey("InseeCode");

                    b.ToTable("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
