name: dotnet Build and Test + Deploy to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: cd backend/SnlMaps && dotnet restore

      - name: Build
        run: cd backend/SnlMaps && dotnet build --no-restore

      - name: Test
        run: cd backend/SnlMaps && dotnet test --no-build --verbosity normal
        env: 
          TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}

      - name: Build the Docker image
        run: cd backend/SnlMaps && docker build -t ombrelin/snlmaps:1.0 . --file SnlMaps.Web/Dockerfile

      - name: Docker login
        run: echo '${{ secrets.DOCKER_TOKEN }}' | docker login --username ombrelin --password-stdin

      - name: Publish to Docker hub
        run: docker push ombrelin/snlmaps:1.0