name: Build angular app + Deploy to github pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: cd frontend && npm install

      - name: Publish to gh pages
        run: cd frontend && ng deploy --base-href=/snl-map/