name: Build angular app + Deploy to github pages

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Publish to gh pages
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.2
        with:
          angular_project_dir: frontend
          base_href: /snl-map/
          deploy_branch: gh-pages
          angular_dist_build_folder: dist/snl-map